# Generated by Django 6.0.5 on 2026-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
